# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6afb0bbd9fa68083043e172ade4dabbe1f8f11a693adb60d33d9cf814e44ccccdf2efde4e711596f5c6a20aac88449f31150b55eba677f80aeb27da7cfcd20d9

test:
  secret_key_base: adbb19464f5c3ad0cc6a17dbd580c4e77552f99fae83e3e4ce1487145dbf735c5a7fb1feefe1666d5cf21bc56fd817376b2f5d6bdd8d39c535c50e28b4ef9146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
